#!/usr/bin/env php
<?php

/* {licenseheader} */

use yii\console\Application;
use yii\helpers\ArrayHelper;

const APP_CONTEXT = 'console';
const APP_ROOT = __DIR__;

require APP_ROOT . '/config/env-local.php';

require APP_ROOT . '/vendor/yiisoft/yii2/Yii.php';
require APP_ROOT . '/vendor/autoload.php';

require APP_ROOT . '/config/bootstrap.php';
/* @noinspection PhpIncludeInspection */
$config = ArrayHelper::merge(
	require APP_ROOT . '/config/0-main.php',
	require APP_ROOT . '/config/1-' . APP_CONTEXT . '.php',
	require APP_ROOT . '/config/2-' . ENV . '.php',
	require APP_ROOT . '/config/3-local.php'
);

exit((new Application($config))->run());
